# Generated by Django 2.2.28 on 2023-04-05 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_groupnotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupnotification',
            name='group_notification',
            field=models.CharField(blank=True, choices=[('Follow', 'Follow'), ('Be Notified', 'Be Notified'), ('Receive Email', 'Receive Email')], max_length=255, null=True),
        ),
    ]
