# Generated by Django 2.2.28 on 2022-12-10 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotificationSetting',
        ),
    ]
