# Generated by Django 2.2.26 on 2022-05-30 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostSubComment',
        ),
    ]
