# Generated by Django 2.2.28 on 2022-12-17 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_flagpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_group_post',
            field=models.BooleanField(default=False),
        ),
    ]
