# Generated by Django 2.2.28 on 2023-01-09 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_is_group_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_multiple_poll',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='is_poll',
            field=models.BooleanField(default=False),
        ),
    ]
