# Generated by Django 2.2.28 on 2023-01-10 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20230109_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='flagpost',
            name='reason_type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
