# Generated by Django 2.2.28 on 2023-02-22 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_flagpost_reason_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='community',
            field=models.CharField(choices=[('Everyone', 'Everyone'), ('Following', 'Following')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='scheduled',
            field=models.CharField(choices=[('6 hours', '6 hours'), ('12 hours', '12 hours'), ('24 hours', '24 hours')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('Friends Only', 'Friends Only'), ('Everyone', 'Everyone')], max_length=255, null=True),
        ),
    ]
