# Generated by Django 2.2 on 2023-02-27 14:44

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_chatimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video_file',
            field=models.FileField(null=True, upload_to=core.utils.get_file_path),
        ),
    ]
