# Generated by Django 2.2.28 on 2023-03-02 17:01

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_post_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='images',
            field=models.FileField(blank=True, null=True, upload_to=core.utils.get_file_path),
        ),
    ]
