# Generated by Django 2.2.28 on 2023-03-02 21:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0011_auto_20230302_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='shared_by',
            field=models.ManyToManyField(null=True, related_name='user_shared_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
