# Generated by Django 2.2.28 on 2023-03-03 13:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_post_shared_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='share_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='share_link',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
