# Generated by Django 2.2.28 on 2023-03-03 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_auto_20230303_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='share_count',
            field=models.IntegerField(default=0),
        ),
    ]
