# Generated by Django 2.2.28 on 2023-03-03 14:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_auto_20230303_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='shared_by',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_shared_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
