# Generated by Django 2.2 on 2023-03-09 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_auto_20230308_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='scheduled',
        ),
        migrations.AddField(
            model_name='post',
            name='scheduled_for',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
