# Generated by Django 2.2.28 on 2023-03-28 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='privacy',
            field=models.CharField(choices=[('public', 'public'), ('following', 'following'), ('only me', 'only me')], default='public', max_length=100, null=True),
        ),
    ]
