# Generated by Django 2.2.28 on 2022-12-20 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20221220_0623'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name_as', models.CharField(max_length=255)),
                ('is_like_profile', models.BooleanField(default=True)),
                ('is_hide_birthday', models.BooleanField(default=False)),
                ('who_can_see_profile', models.CharField(default='Public', max_length=255)),
                ('is_online_status', models.BooleanField(default=True)),
                ('timezone', models.CharField(max_length=255, null=True)),
                ('is_enable_chat', models.BooleanField(default=True)),
                ('allow_new_message_friends', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_comment', models.BooleanField(default=True)),
                ('post_reaction', models.BooleanField(default=True)),
                ('comment_reaction', models.BooleanField(default=True)),
                ('comment_reply', models.BooleanField(default=True)),
                ('share_post', models.BooleanField(default=True)),
                ('liked_my_profile', models.BooleanField(default=True)),
                ('mention', models.BooleanField(default=True)),
                ('new_message', models.BooleanField(default=True)),
                ('friend_request', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
