# Generated by Django 2.2.28 on 2023-01-04 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_notificationpreference_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='latutude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
