# Generated by Django 2.2.28 on 2023-02-22 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_cover_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='bio',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='preference',
            name='first_name',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='preference',
            name='last_name',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='preference',
            name='display_name_as',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
