# Generated by Django 2.2 on 2023-03-09 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20230306_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendsuggestion',
            name='user',
        ),
    ]
