# Generated by Django 2.2.28 on 2023-03-10 14:46

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_remove_friendsuggestion_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='walkthrough',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
